name: pyqt_clock Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python3 x64
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Setup pip packages
        run: |
          python -m pip install PyQt6
          python -m pip install pydub

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          enable-plugins: pyqt6

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyqt_clock_build_linux
          path: build/*.bin

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python3 x64
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Setup pip packages
        run: |
          python -m pip install PyQt6
          python -m pip install pydub
          python -m pip install pyinstaller

      - name: Build with Pyinstaller
        run: |
          pyinstaller -F -w main.py

      #- name: Build with Nuitka
      #uses: Nuitka/Nuitka-Action@main
      #with:
      #nuitka-version: main
      #script-name: main.py
      #onefile: true
      #enable-plugins: pyqt6

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyqt_clock_build_windows
          path: dist/*.exe
