name: pyqt_clock Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python3 x64
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Setup pip packages
        run: |
          python -m pip install PyQt6
          python -m pip install pydub
          python -m pip pyinstaller

      - name: Build with Pyinstaller
        run: |
          pyinstaller -F -w -n main.bin main.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyqt_clock_build_linux
          path: dist/*.bin

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python3 x64
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Setup pip packages
        run: |
          python -m pip install PyQt6
          python -m pip install pydub
          python -m pip install pyinstaller

      - name: Build with Pyinstaller
        run: |
          pyinstaller -F -w main.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyqt_clock_build_windows
          path: dist/*.exe
  releases:
    runs-on: ubuntu-20.04

    needs:
      - build_linux
      - build_windows

    steps:

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'

      - name: Install Tools
        run: sudo apt install p7zip-full

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          draft: false
          tag_name: auto_build
          files: |
            ./repo/dist/*.exe
            ./repo/dist/*.bin
